apiVersion: 1

datasources:
  - name: ClickHouse
    uid: clickhouse
    type: grafana-clickhouse-datasource
    access: proxy
    url: http://clickhouse:8123
    jsonData:
      server: clickhouse
      port: 9000
      protocol: native
      username: grafana
      defaultDatabase: default
    secureJsonData:
      password: grafana
    isDefault: true
    editable: true
    version: 1

  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://alloy:12345/prometheus
    jsonData:
      timeInterval: 15s
    editable: true
    version: 1
