apiVersion: v1
kind: ConfigMap
metadata:
  name: otelcol-config
  namespace: travel-app
data:
  config.yaml: |
    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: "0.0.0.0:4317"
          http:
            endpoint: "0.0.0.0:4318"

    processors:
      batch:

    exporters:
      clickhouse:
        endpoint: tcp://clickhouse:9000
        database: default
        username: grafana
        password: grafana
        logs_table_name: otel_logs
        traces_table_name: otel_traces
        metrics_table_name: otel_metrics
        ttl: 72h
        create_schema: true
        retry_on_failure:
          enabled: true
          initial_interval: 5s
          max_interval: 30s
          max_elapsed_time: 300s

    service:
      pipelines:
        metrics:
          receivers: [otlp]
          processors: [batch]
          exporters: [clickhouse]
        logs:
          receivers: [otlp]
          processors: [batch]
          exporters: [clickhouse]
        traces:
          receivers: [otlp]
          processors: [batch]
          exporters: [clickhouse]
