apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: travel-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ${ECR_REGISTRY}/${ECR_REPO}:frontend-${IMAGE_TAG}
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: travel-app
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "owner=${ECR_REPO},project=travel-app"
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
